sudo: required

services: 
    - docker

before_install:
    - docker build -t bigdev2000/django-docker-cicd -f Dockerfile.dev .
    
script:
    - docker run bigdev2000/django-docker-cicd python manage.py test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-956710473097"
    bucket_path: "docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    script: bash ./deploy.sh 
