sudo: required

services: 
    - docker

before_install:
    - docker build -t bigdev2000/django-docker-cicd -f Dockerfile.dev .

script:
    - docker run bigdev2000/django-docker-cicd python manage.py test
