version: '3'

services: 
    django:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 8000:8000
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: passwordfordatabase
            POSTGRES_PASS: passwordfordatabase
            POSTGRES_DB: database
        ports: 
            - 5432:5432